[build]
target = "index.html"
release = true
dist = "dist"
public_url = "/"

[watch]
ignore = ["./dist"]

[serve]
address = "127.0.0.1"
port = 3000
open = false

[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = ["tailwindcss", "-i", "./styles/input.css", "-o", "./dist/output.css", "--minify"]

[[hooks]]
stage = "build"
command = "npx"
command_arguments = ["tailwindcss", "-i", "./styles/input.css", "-o", "./dist/output.css", "--minify"]
