// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: worktree/v1/sync.proto

package worktreepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StagedObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StagedObject) Reset() {
	*x = StagedObject{}
	mi := &file_worktree_v1_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StagedObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StagedObject) ProtoMessage() {}

func (x *StagedObject) ProtoReflect() protoreflect.Message {
	mi := &file_worktree_v1_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StagedObject.ProtoReflect.Descriptor instead.
func (*StagedObject) Descriptor() ([]byte, []int) {
	return file_worktree_v1_sync_proto_rawDescGZIP(), []int{0}
}

func (x *StagedObject) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StagedObject) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *StagedObject) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StagedObject) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type StageSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Tenant        string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Worktree      string                 `protobuf:"bytes,3,opt,name=worktree,proto3" json:"worktree,omitempty"`
	TreeId        string                 `protobuf:"bytes,4,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	Branch        string                 `protobuf:"bytes,5,opt,name=branch,proto3" json:"branch,omitempty"`
	Objects       []*StagedObject        `protobuf:"bytes,6,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageSnapshotRequest) Reset() {
	*x = StageSnapshotRequest{}
	mi := &file_worktree_v1_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageSnapshotRequest) ProtoMessage() {}

func (x *StageSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worktree_v1_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageSnapshotRequest.ProtoReflect.Descriptor instead.
func (*StageSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_worktree_v1_sync_proto_rawDescGZIP(), []int{1}
}

func (x *StageSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *StageSnapshotRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *StageSnapshotRequest) GetWorktree() string {
	if x != nil {
		return x.Worktree
	}
	return ""
}

func (x *StageSnapshotRequest) GetTreeId() string {
	if x != nil {
		return x.TreeId
	}
	return ""
}

func (x *StageSnapshotRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *StageSnapshotRequest) GetObjects() []*StagedObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

type StageSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Objects       int32                  `protobuf:"varint,3,opt,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageSnapshotResponse) Reset() {
	*x = StageSnapshotResponse{}
	mi := &file_worktree_v1_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageSnapshotResponse) ProtoMessage() {}

func (x *StageSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worktree_v1_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageSnapshotResponse.ProtoReflect.Descriptor instead.
func (*StageSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_worktree_v1_sync_proto_rawDescGZIP(), []int{2}
}

func (x *StageSnapshotResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StageSnapshotResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *StageSnapshotResponse) GetObjects() int32 {
	if x != nil {
		return x.Objects
	}
	return 0
}

type ListStagedSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Worktree      string                 `protobuf:"bytes,2,opt,name=worktree,proto3" json:"worktree,omitempty"`
	Branch        string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStagedSnapshotsRequest) Reset() {
	*x = ListStagedSnapshotsRequest{}
	mi := &file_worktree_v1_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStagedSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStagedSnapshotsRequest) ProtoMessage() {}

func (x *ListStagedSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worktree_v1_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStagedSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListStagedSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_worktree_v1_sync_proto_rawDescGZIP(), []int{3}
}

func (x *ListStagedSnapshotsRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ListStagedSnapshotsRequest) GetWorktree() string {
	if x != nil {
		return x.Worktree
	}
	return ""
}

func (x *ListStagedSnapshotsRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type StagedSnapshotRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Tenant        string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Worktree      string                 `protobuf:"bytes,3,opt,name=worktree,proto3" json:"worktree,omitempty"`
	TreeId        string                 `protobuf:"bytes,4,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	Branch        string                 `protobuf:"bytes,5,opt,name=branch,proto3" json:"branch,omitempty"`
	ObjectIds     []string               `protobuf:"bytes,6,rep,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StagedSnapshotRecord) Reset() {
	*x = StagedSnapshotRecord{}
	mi := &file_worktree_v1_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StagedSnapshotRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StagedSnapshotRecord) ProtoMessage() {}

func (x *StagedSnapshotRecord) ProtoReflect() protoreflect.Message {
	mi := &file_worktree_v1_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StagedSnapshotRecord.ProtoReflect.Descriptor instead.
func (*StagedSnapshotRecord) Descriptor() ([]byte, []int) {
	return file_worktree_v1_sync_proto_rawDescGZIP(), []int{4}
}

func (x *StagedSnapshotRecord) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *StagedSnapshotRecord) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *StagedSnapshotRecord) GetWorktree() string {
	if x != nil {
		return x.Worktree
	}
	return ""
}

func (x *StagedSnapshotRecord) GetTreeId() string {
	if x != nil {
		return x.TreeId
	}
	return ""
}

func (x *StagedSnapshotRecord) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *StagedSnapshotRecord) GetObjectIds() []string {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

func (x *StagedSnapshotRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListStagedSnapshotsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Snapshots     []*StagedSnapshotRecord `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	Count         int32                   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStagedSnapshotsResponse) Reset() {
	*x = ListStagedSnapshotsResponse{}
	mi := &file_worktree_v1_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStagedSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStagedSnapshotsResponse) ProtoMessage() {}

func (x *ListStagedSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worktree_v1_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStagedSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*ListStagedSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_worktree_v1_sync_proto_rawDescGZIP(), []int{5}
}

func (x *ListStagedSnapshotsResponse) GetSnapshots() []*StagedSnapshotRecord {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

func (x *ListStagedSnapshotsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_worktree_v1_sync_proto protoreflect.FileDescriptor

const file_worktree_v1_sync_proto_rawDesc = "" +
	"\n" +
	"\x16worktree/v1/sync.proto\x12\vworktree.v1\"d\n" +
	"\fStagedObject\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\"\xd1\x01\n" +
	"\x14StageSnapshotRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12\x1a\n" +
	"\bworktree\x18\x03 \x01(\tR\bworktree\x12\x17\n" +
	"\atree_id\x18\x04 \x01(\tR\x06treeId\x12\x16\n" +
	"\x06branch\x18\x05 \x01(\tR\x06branch\x123\n" +
	"\aobjects\x18\x06 \x03(\v2\x19.worktree.v1.StagedObjectR\aobjects\"j\n" +
	"\x15StageSnapshotResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\x12\x18\n" +
	"\aobjects\x18\x03 \x01(\x05R\aobjects\"h\n" +
	"\x1aListStagedSnapshotsRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1a\n" +
	"\bworktree\x18\x02 \x01(\tR\bworktree\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\"\xda\x01\n" +
	"\x14StagedSnapshotRecord\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12\x1a\n" +
	"\bworktree\x18\x03 \x01(\tR\bworktree\x12\x17\n" +
	"\atree_id\x18\x04 \x01(\tR\x06treeId\x12\x16\n" +
	"\x06branch\x18\x05 \x01(\tR\x06branch\x12\x1d\n" +
	"\n" +
	"object_ids\x18\x06 \x03(\tR\tobjectIds\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"t\n" +
	"\x1bListStagedSnapshotsResponse\x12?\n" +
	"\tsnapshots\x18\x01 \x03(\v2!.worktree.v1.StagedSnapshotRecordR\tsnapshots\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2\xcf\x01\n" +
	"\vSyncService\x12V\n" +
	"\rStageSnapshot\x12!.worktree.v1.StageSnapshotRequest\x1a\".worktree.v1.StageSnapshotResponse\x12h\n" +
	"\x13ListStagedSnapshots\x12'.worktree.v1.ListStagedSnapshotsRequest\x1a(.worktree.v1.ListStagedSnapshotsResponseB@Z>github.com/ramizik/worktree/server-go/internal/grpc/worktreepbb\x06proto3"

var (
	file_worktree_v1_sync_proto_rawDescOnce sync.Once
	file_worktree_v1_sync_proto_rawDescData []byte
)

func file_worktree_v1_sync_proto_rawDescGZIP() []byte {
	file_worktree_v1_sync_proto_rawDescOnce.Do(func() {
		file_worktree_v1_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worktree_v1_sync_proto_rawDesc), len(file_worktree_v1_sync_proto_rawDesc)))
	})
	return file_worktree_v1_sync_proto_rawDescData
}

var file_worktree_v1_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_worktree_v1_sync_proto_goTypes = []any{
	(*StagedObject)(nil),                // 0: worktree.v1.StagedObject
	(*StageSnapshotRequest)(nil),        // 1: worktree.v1.StageSnapshotRequest
	(*StageSnapshotResponse)(nil),       // 2: worktree.v1.StageSnapshotResponse
	(*ListStagedSnapshotsRequest)(nil),  // 3: worktree.v1.ListStagedSnapshotsRequest
	(*StagedSnapshotRecord)(nil),        // 4: worktree.v1.StagedSnapshotRecord
	(*ListStagedSnapshotsResponse)(nil), // 5: worktree.v1.ListStagedSnapshotsResponse
}
var file_worktree_v1_sync_proto_depIdxs = []int32{
	0, // 0: worktree.v1.StageSnapshotRequest.objects:type_name -> worktree.v1.StagedObject
	4, // 1: worktree.v1.ListStagedSnapshotsResponse.snapshots:type_name -> worktree.v1.StagedSnapshotRecord
	1, // 2: worktree.v1.SyncService.StageSnapshot:input_type -> worktree.v1.StageSnapshotRequest
	3, // 3: worktree.v1.SyncService.ListStagedSnapshots:input_type -> worktree.v1.ListStagedSnapshotsRequest
	2, // 4: worktree.v1.SyncService.StageSnapshot:output_type -> worktree.v1.StageSnapshotResponse
	5, // 5: worktree.v1.SyncService.ListStagedSnapshots:output_type -> worktree.v1.ListStagedSnapshotsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_worktree_v1_sync_proto_init() }
func file_worktree_v1_sync_proto_init() {
	if File_worktree_v1_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worktree_v1_sync_proto_rawDesc), len(file_worktree_v1_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worktree_v1_sync_proto_goTypes,
		DependencyIndexes: file_worktree_v1_sync_proto_depIdxs,
		MessageInfos:      file_worktree_v1_sync_proto_msgTypes,
	}.Build()
	File_worktree_v1_sync_proto = out.File
	file_worktree_v1_sync_proto_goTypes = nil
	file_worktree_v1_sync_proto_depIdxs = nil
}
