// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: worktree/v1/sync.proto

package worktreepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncService_StageSnapshot_FullMethodName       = "/worktree.v1.SyncService/StageSnapshot"
	SyncService_ListStagedSnapshots_FullMethodName = "/worktree.v1.SyncService/ListStagedSnapshots"
)

// SyncServiceClient is the client API for SyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SyncService handles staged snapshot uploads and listings between client and server.
type SyncServiceClient interface {
	// StageSnapshot uploads a local snapshot as staged work visible to teammates.
	// Idempotent on snapshot_id.
	StageSnapshot(ctx context.Context, in *StageSnapshotRequest, opts ...grpc.CallOption) (*StageSnapshotResponse, error)
	// ListStagedSnapshots returns staged snapshots visible to the caller.
	ListStagedSnapshots(ctx context.Context, in *ListStagedSnapshotsRequest, opts ...grpc.CallOption) (*ListStagedSnapshotsResponse, error)
}

type syncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncServiceClient(cc grpc.ClientConnInterface) SyncServiceClient {
	return &syncServiceClient{cc}
}

func (c *syncServiceClient) StageSnapshot(ctx context.Context, in *StageSnapshotRequest, opts ...grpc.CallOption) (*StageSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StageSnapshotResponse)
	err := c.cc.Invoke(ctx, SyncService_StageSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) ListStagedSnapshots(ctx context.Context, in *ListStagedSnapshotsRequest, opts ...grpc.CallOption) (*ListStagedSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStagedSnapshotsResponse)
	err := c.cc.Invoke(ctx, SyncService_ListStagedSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncServiceServer is the server API for SyncService service.
// All implementations must embed UnimplementedSyncServiceServer
// for forward compatibility.
//
// SyncService handles staged snapshot uploads and listings between client and server.
type SyncServiceServer interface {
	// StageSnapshot uploads a local snapshot as staged work visible to teammates.
	// Idempotent on snapshot_id.
	StageSnapshot(context.Context, *StageSnapshotRequest) (*StageSnapshotResponse, error)
	// ListStagedSnapshots returns staged snapshots visible to the caller.
	ListStagedSnapshots(context.Context, *ListStagedSnapshotsRequest) (*ListStagedSnapshotsResponse, error)
	mustEmbedUnimplementedSyncServiceServer()
}

// UnimplementedSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncServiceServer struct{}

func (UnimplementedSyncServiceServer) StageSnapshot(context.Context, *StageSnapshotRequest) (*StageSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StageSnapshot not implemented")
}
func (UnimplementedSyncServiceServer) ListStagedSnapshots(context.Context, *ListStagedSnapshotsRequest) (*ListStagedSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStagedSnapshots not implemented")
}
func (UnimplementedSyncServiceServer) mustEmbedUnimplementedSyncServiceServer() {}
func (UnimplementedSyncServiceServer) testEmbeddedByValue()                     {}

// UnsafeSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncServiceServer will
// result in compilation errors.
type UnsafeSyncServiceServer interface {
	mustEmbedUnimplementedSyncServiceServer()
}

func RegisterSyncServiceServer(s grpc.ServiceRegistrar, srv SyncServiceServer) {
	// If the following call panics, it indicates UnimplementedSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncService_ServiceDesc, srv)
}

func _SyncService_StageSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StageSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).StageSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_StageSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).StageSnapshot(ctx, req.(*StageSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_ListStagedSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStagedSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).ListStagedSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_ListStagedSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).ListStagedSnapshots(ctx, req.(*ListStagedSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncService_ServiceDesc is the grpc.ServiceDesc for SyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "worktree.v1.SyncService",
	HandlerType: (*SyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StageSnapshot",
			Handler:    _SyncService_StageSnapshot_Handler,
		},
		{
			MethodName: "ListStagedSnapshots",
			Handler:    _SyncService_ListStagedSnapshots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worktree/v1/sync.proto",
}
