// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sync.proto

// W0rkTree sync protocol — wire format for communication between
// the local bgprocess (worktree-bg) and the remote server (worktree-server,
// future Go impl at services/server-go/).
//
// Mirrors the hand-coded Rust types in
//   crates/worktree-protocol/src/feature/sync_protocol.rs
// which remain alongside this codegen output during the WT-PROTO-* migration.
//
// Conventions: see crates/worktree-protocol/proto/CONVENTIONS.md
//   - all IDs are wrapped messages (cross-language type safety)
//   - field tag 100-199 is reserved on every message for additive expansion
//   - timestamps use google.protobuf.Timestamp
//   - payload-bearing Rust enums map to proto `oneof`; unit-only Rust enums
//     map to proto `enum` with _UNSPECIFIED = 0.

package syncpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncMessageType int32

const (
	SyncMessageType_SYNC_MESSAGE_TYPE_UNSPECIFIED SyncMessageType = 0
	// Staged snapshot sync
	SyncMessageType_SYNC_MESSAGE_TYPE_STAGE_UPLOAD SyncMessageType = 1
	SyncMessageType_SYNC_MESSAGE_TYPE_STAGE_ACK    SyncMessageType = 2
	// Branch push/pull
	SyncMessageType_SYNC_MESSAGE_TYPE_PUSH_REQUEST  SyncMessageType = 3
	SyncMessageType_SYNC_MESSAGE_TYPE_PUSH_RESPONSE SyncMessageType = 4
	SyncMessageType_SYNC_MESSAGE_TYPE_PULL_REQUEST  SyncMessageType = 5
	SyncMessageType_SYNC_MESSAGE_TYPE_PULL_RESPONSE SyncMessageType = 6
	// Object transfer
	SyncMessageType_SYNC_MESSAGE_TYPE_HAVE_WANT       SyncMessageType = 7
	SyncMessageType_SYNC_MESSAGE_TYPE_OBJECT_TRANSFER SyncMessageType = 8
	// Access config sync
	SyncMessageType_SYNC_MESSAGE_TYPE_ACCESS_CONFIG_SYNC SyncMessageType = 9
	// Tag sync
	SyncMessageType_SYNC_MESSAGE_TYPE_TAG_SYNC SyncMessageType = 10
	// Chunk transfer (large files)
	SyncMessageType_SYNC_MESSAGE_TYPE_CHUNK_UPLOAD   SyncMessageType = 11
	SyncMessageType_SYNC_MESSAGE_TYPE_CHUNK_DOWNLOAD SyncMessageType = 12
	// Health
	SyncMessageType_SYNC_MESSAGE_TYPE_PING SyncMessageType = 13
	SyncMessageType_SYNC_MESSAGE_TYPE_PONG SyncMessageType = 14
)

// Enum value maps for SyncMessageType.
var (
	SyncMessageType_name = map[int32]string{
		0:  "SYNC_MESSAGE_TYPE_UNSPECIFIED",
		1:  "SYNC_MESSAGE_TYPE_STAGE_UPLOAD",
		2:  "SYNC_MESSAGE_TYPE_STAGE_ACK",
		3:  "SYNC_MESSAGE_TYPE_PUSH_REQUEST",
		4:  "SYNC_MESSAGE_TYPE_PUSH_RESPONSE",
		5:  "SYNC_MESSAGE_TYPE_PULL_REQUEST",
		6:  "SYNC_MESSAGE_TYPE_PULL_RESPONSE",
		7:  "SYNC_MESSAGE_TYPE_HAVE_WANT",
		8:  "SYNC_MESSAGE_TYPE_OBJECT_TRANSFER",
		9:  "SYNC_MESSAGE_TYPE_ACCESS_CONFIG_SYNC",
		10: "SYNC_MESSAGE_TYPE_TAG_SYNC",
		11: "SYNC_MESSAGE_TYPE_CHUNK_UPLOAD",
		12: "SYNC_MESSAGE_TYPE_CHUNK_DOWNLOAD",
		13: "SYNC_MESSAGE_TYPE_PING",
		14: "SYNC_MESSAGE_TYPE_PONG",
	}
	SyncMessageType_value = map[string]int32{
		"SYNC_MESSAGE_TYPE_UNSPECIFIED":        0,
		"SYNC_MESSAGE_TYPE_STAGE_UPLOAD":       1,
		"SYNC_MESSAGE_TYPE_STAGE_ACK":          2,
		"SYNC_MESSAGE_TYPE_PUSH_REQUEST":       3,
		"SYNC_MESSAGE_TYPE_PUSH_RESPONSE":      4,
		"SYNC_MESSAGE_TYPE_PULL_REQUEST":       5,
		"SYNC_MESSAGE_TYPE_PULL_RESPONSE":      6,
		"SYNC_MESSAGE_TYPE_HAVE_WANT":          7,
		"SYNC_MESSAGE_TYPE_OBJECT_TRANSFER":    8,
		"SYNC_MESSAGE_TYPE_ACCESS_CONFIG_SYNC": 9,
		"SYNC_MESSAGE_TYPE_TAG_SYNC":           10,
		"SYNC_MESSAGE_TYPE_CHUNK_UPLOAD":       11,
		"SYNC_MESSAGE_TYPE_CHUNK_DOWNLOAD":     12,
		"SYNC_MESSAGE_TYPE_PING":               13,
		"SYNC_MESSAGE_TYPE_PONG":               14,
	}
)

func (x SyncMessageType) Enum() *SyncMessageType {
	p := new(SyncMessageType)
	*p = x
	return p
}

func (x SyncMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_sync_proto_enumTypes[0].Descriptor()
}

func (SyncMessageType) Type() protoreflect.EnumType {
	return &file_sync_proto_enumTypes[0]
}

func (x SyncMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncMessageType.Descriptor instead.
func (SyncMessageType) EnumDescriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

// Kind of access config being synced.
type AccessConfigType int32

const (
	AccessConfigType_ACCESS_CONFIG_TYPE_UNSPECIFIED       AccessConfigType = 0
	AccessConfigType_ACCESS_CONFIG_TYPE_ROLES             AccessConfigType = 1
	AccessConfigType_ACCESS_CONFIG_TYPE_POLICIES          AccessConfigType = 2
	AccessConfigType_ACCESS_CONFIG_TYPE_TENANT_ACCESS     AccessConfigType = 3
	AccessConfigType_ACCESS_CONFIG_TYPE_BRANCH_PROTECTION AccessConfigType = 4
	AccessConfigType_ACCESS_CONFIG_TYPE_LICENSE           AccessConfigType = 5
)

// Enum value maps for AccessConfigType.
var (
	AccessConfigType_name = map[int32]string{
		0: "ACCESS_CONFIG_TYPE_UNSPECIFIED",
		1: "ACCESS_CONFIG_TYPE_ROLES",
		2: "ACCESS_CONFIG_TYPE_POLICIES",
		3: "ACCESS_CONFIG_TYPE_TENANT_ACCESS",
		4: "ACCESS_CONFIG_TYPE_BRANCH_PROTECTION",
		5: "ACCESS_CONFIG_TYPE_LICENSE",
	}
	AccessConfigType_value = map[string]int32{
		"ACCESS_CONFIG_TYPE_UNSPECIFIED":       0,
		"ACCESS_CONFIG_TYPE_ROLES":             1,
		"ACCESS_CONFIG_TYPE_POLICIES":          2,
		"ACCESS_CONFIG_TYPE_TENANT_ACCESS":     3,
		"ACCESS_CONFIG_TYPE_BRANCH_PROTECTION": 4,
		"ACCESS_CONFIG_TYPE_LICENSE":           5,
	}
)

func (x AccessConfigType) Enum() *AccessConfigType {
	p := new(AccessConfigType)
	*p = x
	return p
}

func (x AccessConfigType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessConfigType) Descriptor() protoreflect.EnumDescriptor {
	return file_sync_proto_enumTypes[1].Descriptor()
}

func (AccessConfigType) Type() protoreflect.EnumType {
	return &file_sync_proto_enumTypes[1]
}

func (x AccessConfigType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessConfigType.Descriptor instead.
func (AccessConfigType) EnumDescriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{1}
}

// Unique identifier for a worktree.
type TreeId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeId) Reset() {
	*x = TreeId{}
	mi := &file_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeId) ProtoMessage() {}

func (x *TreeId) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeId.ProtoReflect.Descriptor instead.
func (*TreeId) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

func (x *TreeId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Unique identifier for a snapshot.
type SnapshotId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotId) Reset() {
	*x = SnapshotId{}
	mi := &file_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotId) ProtoMessage() {}

func (x *SnapshotId) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotId.ProtoReflect.Descriptor instead.
func (*SnapshotId) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Unique identifier for a branch.
type BranchId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BranchId) Reset() {
	*x = BranchId{}
	mi := &file_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BranchId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchId) ProtoMessage() {}

func (x *BranchId) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchId.ProtoReflect.Descriptor instead.
func (*BranchId) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{2}
}

func (x *BranchId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Unique identifier for a tenant in multi-tenant setups.
type TenantId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantId) Reset() {
	*x = TenantId{}
	mi := &file_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantId) ProtoMessage() {}

func (x *TenantId) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantId.ProtoReflect.Descriptor instead.
func (*TenantId) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{3}
}

func (x *TenantId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Unique identifier for a user account.
type AccountId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountId) Reset() {
	*x = AccountId{}
	mi := &file_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountId) ProtoMessage() {}

func (x *AccountId) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountId.ProtoReflect.Descriptor instead.
func (*AccountId) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{4}
}

func (x *AccountId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// BLAKE3 content hash — 32 bytes.
type ContentHash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentHash) Reset() {
	*x = ContentHash{}
	mi := &file_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentHash) ProtoMessage() {}

func (x *ContentHash) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentHash.ProtoReflect.Descriptor instead.
func (*ContentHash) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{5}
}

func (x *ContentHash) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Client announces which objects it has.
type HaveMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        []*ContentHash         `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HaveMessage) Reset() {
	*x = HaveMessage{}
	mi := &file_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HaveMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HaveMessage) ProtoMessage() {}

func (x *HaveMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HaveMessage.ProtoReflect.Descriptor instead.
func (*HaveMessage) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{6}
}

func (x *HaveMessage) GetHashes() []*ContentHash {
	if x != nil {
		return x.Hashes
	}
	return nil
}

// Client announces which objects it wants.
type WantMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        []*ContentHash         `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WantMessage) Reset() {
	*x = WantMessage{}
	mi := &file_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WantMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WantMessage) ProtoMessage() {}

func (x *WantMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WantMessage.ProtoReflect.Descriptor instead.
func (*WantMessage) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{7}
}

func (x *WantMessage) GetHashes() []*ContentHash {
	if x != nil {
		return x.Hashes
	}
	return nil
}

// Server responds with the set of objects to transfer.
type ObjectTransferPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectsToSend []*ContentHash         `protobuf:"bytes,1,rep,name=objects_to_send,json=objectsToSend,proto3" json:"objects_to_send,omitempty"`
	TotalSize     uint64                 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectTransferPlan) Reset() {
	*x = ObjectTransferPlan{}
	mi := &file_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectTransferPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectTransferPlan) ProtoMessage() {}

func (x *ObjectTransferPlan) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectTransferPlan.ProtoReflect.Descriptor instead.
func (*ObjectTransferPlan) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{8}
}

func (x *ObjectTransferPlan) GetObjectsToSend() []*ContentHash {
	if x != nil {
		return x.ObjectsToSend
	}
	return nil
}

func (x *ObjectTransferPlan) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// Combined have/want negotiation request — sent by client; server replies
// with ObjectTransferPlan. The Rust side currently keeps HaveMessage and
// WantMessage as separate types (matched here) but the gRPC RPC takes them
// together for round-trip efficiency.
type NegotiateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Have          *HaveMessage           `protobuf:"bytes,1,opt,name=have,proto3" json:"have,omitempty"`
	Want          *WantMessage           `protobuf:"bytes,2,opt,name=want,proto3" json:"want,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NegotiateRequest) Reset() {
	*x = NegotiateRequest{}
	mi := &file_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NegotiateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NegotiateRequest) ProtoMessage() {}

func (x *NegotiateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NegotiateRequest.ProtoReflect.Descriptor instead.
func (*NegotiateRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{9}
}

func (x *NegotiateRequest) GetHave() *HaveMessage {
	if x != nil {
		return x.Have
	}
	return nil
}

func (x *NegotiateRequest) GetWant() *WantMessage {
	if x != nil {
		return x.Want
	}
	return nil
}

// Request to push a branch tip to the server.
type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      *TenantId              `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TreeId        *TreeId                `protobuf:"bytes,2,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	BranchId      *BranchId              `protobuf:"bytes,3,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	BranchName    string                 `protobuf:"bytes,4,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	OldTip        *SnapshotId            `protobuf:"bytes,5,opt,name=old_tip,json=oldTip,proto3,oneof" json:"old_tip,omitempty"`
	NewTip        *SnapshotId            `protobuf:"bytes,6,opt,name=new_tip,json=newTip,proto3" json:"new_tip,omitempty"`
	SnapshotChain []*SnapshotId          `protobuf:"bytes,7,rep,name=snapshot_chain,json=snapshotChain,proto3" json:"snapshot_chain,omitempty"`
	AccountId     *AccountId             `protobuf:"bytes,8,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_sync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{10}
}

func (x *PushRequest) GetTenantId() *TenantId {
	if x != nil {
		return x.TenantId
	}
	return nil
}

func (x *PushRequest) GetTreeId() *TreeId {
	if x != nil {
		return x.TreeId
	}
	return nil
}

func (x *PushRequest) GetBranchId() *BranchId {
	if x != nil {
		return x.BranchId
	}
	return nil
}

func (x *PushRequest) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *PushRequest) GetOldTip() *SnapshotId {
	if x != nil {
		return x.OldTip
	}
	return nil
}

func (x *PushRequest) GetNewTip() *SnapshotId {
	if x != nil {
		return x.NewTip
	}
	return nil
}

func (x *PushRequest) GetSnapshotChain() []*SnapshotId {
	if x != nil {
		return x.SnapshotChain
	}
	return nil
}

func (x *PushRequest) GetAccountId() *AccountId {
	if x != nil {
		return x.AccountId
	}
	return nil
}

// Server response to a push.
type PushResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Accepted        bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectionReason *PushRejection         `protobuf:"bytes,2,opt,name=rejection_reason,json=rejectionReason,proto3,oneof" json:"rejection_reason,omitempty"`
	NewTip          *SnapshotId            `protobuf:"bytes,3,opt,name=new_tip,json=newTip,proto3,oneof" json:"new_tip,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_sync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{11}
}

func (x *PushResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PushResponse) GetRejectionReason() *PushRejection {
	if x != nil {
		return x.RejectionReason
	}
	return nil
}

func (x *PushResponse) GetNewTip() *SnapshotId {
	if x != nil {
		return x.NewTip
	}
	return nil
}

// Reasons a push may be rejected. Sum type with per-variant payload —
// represented as a oneof per CONVENTIONS.md §3.
type PushRejection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Reason:
	//
	//	*PushRejection_ConflictDetected_
	//	*PushRejection_BranchProtection_
	//	*PushRejection_AccessDenied_
	//	*PushRejection_LicenseViolation_
	//	*PushRejection_CiChecksFailed_
	//	*PushRejection_ReviewRequired_
	//	*PushRejection_QuotaExceeded_
	Reason        isPushRejection_Reason `protobuf_oneof:"reason"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRejection) Reset() {
	*x = PushRejection{}
	mi := &file_sync_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRejection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRejection) ProtoMessage() {}

func (x *PushRejection) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRejection.ProtoReflect.Descriptor instead.
func (*PushRejection) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{12}
}

func (x *PushRejection) GetReason() isPushRejection_Reason {
	if x != nil {
		return x.Reason
	}
	return nil
}

func (x *PushRejection) GetConflictDetected() *PushRejection_ConflictDetected {
	if x != nil {
		if x, ok := x.Reason.(*PushRejection_ConflictDetected_); ok {
			return x.ConflictDetected
		}
	}
	return nil
}

func (x *PushRejection) GetBranchProtection() *PushRejection_BranchProtection {
	if x != nil {
		if x, ok := x.Reason.(*PushRejection_BranchProtection_); ok {
			return x.BranchProtection
		}
	}
	return nil
}

func (x *PushRejection) GetAccessDenied() *PushRejection_AccessDenied {
	if x != nil {
		if x, ok := x.Reason.(*PushRejection_AccessDenied_); ok {
			return x.AccessDenied
		}
	}
	return nil
}

func (x *PushRejection) GetLicenseViolation() *PushRejection_LicenseViolation {
	if x != nil {
		if x, ok := x.Reason.(*PushRejection_LicenseViolation_); ok {
			return x.LicenseViolation
		}
	}
	return nil
}

func (x *PushRejection) GetCiChecksFailed() *PushRejection_CiChecksFailed {
	if x != nil {
		if x, ok := x.Reason.(*PushRejection_CiChecksFailed_); ok {
			return x.CiChecksFailed
		}
	}
	return nil
}

func (x *PushRejection) GetReviewRequired() *PushRejection_ReviewRequired {
	if x != nil {
		if x, ok := x.Reason.(*PushRejection_ReviewRequired_); ok {
			return x.ReviewRequired
		}
	}
	return nil
}

func (x *PushRejection) GetQuotaExceeded() *PushRejection_QuotaExceeded {
	if x != nil {
		if x, ok := x.Reason.(*PushRejection_QuotaExceeded_); ok {
			return x.QuotaExceeded
		}
	}
	return nil
}

type isPushRejection_Reason interface {
	isPushRejection_Reason()
}

type PushRejection_ConflictDetected_ struct {
	ConflictDetected *PushRejection_ConflictDetected `protobuf:"bytes,1,opt,name=conflict_detected,json=conflictDetected,proto3,oneof"`
}

type PushRejection_BranchProtection_ struct {
	BranchProtection *PushRejection_BranchProtection `protobuf:"bytes,2,opt,name=branch_protection,json=branchProtection,proto3,oneof"`
}

type PushRejection_AccessDenied_ struct {
	AccessDenied *PushRejection_AccessDenied `protobuf:"bytes,3,opt,name=access_denied,json=accessDenied,proto3,oneof"`
}

type PushRejection_LicenseViolation_ struct {
	LicenseViolation *PushRejection_LicenseViolation `protobuf:"bytes,4,opt,name=license_violation,json=licenseViolation,proto3,oneof"`
}

type PushRejection_CiChecksFailed_ struct {
	CiChecksFailed *PushRejection_CiChecksFailed `protobuf:"bytes,5,opt,name=ci_checks_failed,json=ciChecksFailed,proto3,oneof"`
}

type PushRejection_ReviewRequired_ struct {
	ReviewRequired *PushRejection_ReviewRequired `protobuf:"bytes,6,opt,name=review_required,json=reviewRequired,proto3,oneof"`
}

type PushRejection_QuotaExceeded_ struct {
	QuotaExceeded *PushRejection_QuotaExceeded `protobuf:"bytes,7,opt,name=quota_exceeded,json=quotaExceeded,proto3,oneof"`
}

func (*PushRejection_ConflictDetected_) isPushRejection_Reason() {}

func (*PushRejection_BranchProtection_) isPushRejection_Reason() {}

func (*PushRejection_AccessDenied_) isPushRejection_Reason() {}

func (*PushRejection_LicenseViolation_) isPushRejection_Reason() {}

func (*PushRejection_CiChecksFailed_) isPushRejection_Reason() {}

func (*PushRejection_ReviewRequired_) isPushRejection_Reason() {}

func (*PushRejection_QuotaExceeded_) isPushRejection_Reason() {}

// Request to pull updates from the server.
type PullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      *TenantId              `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TreeId        *TreeId                `protobuf:"bytes,2,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	BranchId      *BranchId              `protobuf:"bytes,3,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	CurrentTip    *SnapshotId            `protobuf:"bytes,4,opt,name=current_tip,json=currentTip,proto3,oneof" json:"current_tip,omitempty"`
	AccountId     *AccountId             `protobuf:"bytes,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Depth         *uint32                `protobuf:"varint,6,opt,name=depth,proto3,oneof" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_sync_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{13}
}

func (x *PullRequest) GetTenantId() *TenantId {
	if x != nil {
		return x.TenantId
	}
	return nil
}

func (x *PullRequest) GetTreeId() *TreeId {
	if x != nil {
		return x.TreeId
	}
	return nil
}

func (x *PullRequest) GetBranchId() *BranchId {
	if x != nil {
		return x.BranchId
	}
	return nil
}

func (x *PullRequest) GetCurrentTip() *SnapshotId {
	if x != nil {
		return x.CurrentTip
	}
	return nil
}

func (x *PullRequest) GetAccountId() *AccountId {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *PullRequest) GetDepth() uint32 {
	if x != nil && x.Depth != nil {
		return *x.Depth
	}
	return 0
}

// Server response with updates.
type PullResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HasUpdates     bool                   `protobuf:"varint,1,opt,name=has_updates,json=hasUpdates,proto3" json:"has_updates,omitempty"`
	NewTip         *SnapshotId            `protobuf:"bytes,2,opt,name=new_tip,json=newTip,proto3,oneof" json:"new_tip,omitempty"`
	SnapshotChain  []*SnapshotId          `protobuf:"bytes,3,rep,name=snapshot_chain,json=snapshotChain,proto3" json:"snapshot_chain,omitempty"`
	ObjectsToFetch []*ContentHash         `protobuf:"bytes,4,rep,name=objects_to_fetch,json=objectsToFetch,proto3" json:"objects_to_fetch,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PullResponse) Reset() {
	*x = PullResponse{}
	mi := &file_sync_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullResponse) ProtoMessage() {}

func (x *PullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullResponse.ProtoReflect.Descriptor instead.
func (*PullResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{14}
}

func (x *PullResponse) GetHasUpdates() bool {
	if x != nil {
		return x.HasUpdates
	}
	return false
}

func (x *PullResponse) GetNewTip() *SnapshotId {
	if x != nil {
		return x.NewTip
	}
	return nil
}

func (x *PullResponse) GetSnapshotChain() []*SnapshotId {
	if x != nil {
		return x.SnapshotChain
	}
	return nil
}

func (x *PullResponse) GetObjectsToFetch() []*ContentHash {
	if x != nil {
		return x.ObjectsToFetch
	}
	return nil
}

// Upload a staged snapshot to the server.
type StageUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      *TenantId              `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TreeId        *TreeId                `protobuf:"bytes,2,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	BranchId      *BranchId              `protobuf:"bytes,3,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	BranchName    string                 `protobuf:"bytes,4,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	SnapshotId    *SnapshotId            `protobuf:"bytes,5,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	FilesChanged  []string               `protobuf:"bytes,6,rep,name=files_changed,json=filesChanged,proto3" json:"files_changed,omitempty"`
	FilesAdded    uint32                 `protobuf:"varint,7,opt,name=files_added,json=filesAdded,proto3" json:"files_added,omitempty"`
	FilesModified uint32                 `protobuf:"varint,8,opt,name=files_modified,json=filesModified,proto3" json:"files_modified,omitempty"`
	FilesDeleted  uint32                 `protobuf:"varint,9,opt,name=files_deleted,json=filesDeleted,proto3" json:"files_deleted,omitempty"`
	Message       *string                `protobuf:"bytes,10,opt,name=message,proto3,oneof" json:"message,omitempty"`
	AccountId     *AccountId             `protobuf:"bytes,11,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageUploadRequest) Reset() {
	*x = StageUploadRequest{}
	mi := &file_sync_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageUploadRequest) ProtoMessage() {}

func (x *StageUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageUploadRequest.ProtoReflect.Descriptor instead.
func (*StageUploadRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{15}
}

func (x *StageUploadRequest) GetTenantId() *TenantId {
	if x != nil {
		return x.TenantId
	}
	return nil
}

func (x *StageUploadRequest) GetTreeId() *TreeId {
	if x != nil {
		return x.TreeId
	}
	return nil
}

func (x *StageUploadRequest) GetBranchId() *BranchId {
	if x != nil {
		return x.BranchId
	}
	return nil
}

func (x *StageUploadRequest) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *StageUploadRequest) GetSnapshotId() *SnapshotId {
	if x != nil {
		return x.SnapshotId
	}
	return nil
}

func (x *StageUploadRequest) GetFilesChanged() []string {
	if x != nil {
		return x.FilesChanged
	}
	return nil
}

func (x *StageUploadRequest) GetFilesAdded() uint32 {
	if x != nil {
		return x.FilesAdded
	}
	return 0
}

func (x *StageUploadRequest) GetFilesModified() uint32 {
	if x != nil {
		return x.FilesModified
	}
	return 0
}

func (x *StageUploadRequest) GetFilesDeleted() uint32 {
	if x != nil {
		return x.FilesDeleted
	}
	return 0
}

func (x *StageUploadRequest) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *StageUploadRequest) GetAccountId() *AccountId {
	if x != nil {
		return x.AccountId
	}
	return nil
}

// Server acknowledgment.
type StageUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageUploadResponse) Reset() {
	*x = StageUploadResponse{}
	mi := &file_sync_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageUploadResponse) ProtoMessage() {}

func (x *StageUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageUploadResponse.ProtoReflect.Descriptor instead.
func (*StageUploadResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{16}
}

func (x *StageUploadResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *StageUploadResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// Sync access configuration changes.
type AccessConfigSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      *TenantId              `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ConfigType    AccessConfigType       `protobuf:"varint,2,opt,name=config_type,json=configType,proto3,enum=worktree.sync.v1.AccessConfigType" json:"config_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ConfigHash    *ContentHash           `protobuf:"bytes,4,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	AccountId     *AccountId             `protobuf:"bytes,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessConfigSyncRequest) Reset() {
	*x = AccessConfigSyncRequest{}
	mi := &file_sync_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessConfigSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessConfigSyncRequest) ProtoMessage() {}

func (x *AccessConfigSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessConfigSyncRequest.ProtoReflect.Descriptor instead.
func (*AccessConfigSyncRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{17}
}

func (x *AccessConfigSyncRequest) GetTenantId() *TenantId {
	if x != nil {
		return x.TenantId
	}
	return nil
}

func (x *AccessConfigSyncRequest) GetConfigType() AccessConfigType {
	if x != nil {
		return x.ConfigType
	}
	return AccessConfigType_ACCESS_CONFIG_TYPE_UNSPECIFIED
}

func (x *AccessConfigSyncRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *AccessConfigSyncRequest) GetConfigHash() *ContentHash {
	if x != nil {
		return x.ConfigHash
	}
	return nil
}

func (x *AccessConfigSyncRequest) GetAccountId() *AccountId {
	if x != nil {
		return x.AccountId
	}
	return nil
}

// Server validation response.
type AccessConfigSyncResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Accepted         bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ValidationErrors []string               `protobuf:"bytes,2,rep,name=validation_errors,json=validationErrors,proto3" json:"validation_errors,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AccessConfigSyncResponse) Reset() {
	*x = AccessConfigSyncResponse{}
	mi := &file_sync_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessConfigSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessConfigSyncResponse) ProtoMessage() {}

func (x *AccessConfigSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessConfigSyncResponse.ProtoReflect.Descriptor instead.
func (*AccessConfigSyncResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{18}
}

func (x *AccessConfigSyncResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AccessConfigSyncResponse) GetValidationErrors() []string {
	if x != nil {
		return x.ValidationErrors
	}
	return nil
}

// Tracks the sync state between client and server.
// Not transmitted on the wire today — kept here for parity with Rust
// domain types, may move to a local-state .proto if it grows.
type SyncState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LastSync       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_sync,json=lastSync,proto3,oneof" json:"last_sync,omitempty"`
	LocalTip       *SnapshotId            `protobuf:"bytes,2,opt,name=local_tip,json=localTip,proto3,oneof" json:"local_tip,omitempty"`
	RemoteTip      *SnapshotId            `protobuf:"bytes,3,opt,name=remote_tip,json=remoteTip,proto3,oneof" json:"remote_tip,omitempty"`
	PendingStaged  uint32                 `protobuf:"varint,4,opt,name=pending_staged,json=pendingStaged,proto3" json:"pending_staged,omitempty"`
	PendingObjects uint32                 `protobuf:"varint,5,opt,name=pending_objects,json=pendingObjects,proto3" json:"pending_objects,omitempty"`
	IsSyncing      bool                   `protobuf:"varint,6,opt,name=is_syncing,json=isSyncing,proto3" json:"is_syncing,omitempty"`
	Offline        bool                   `protobuf:"varint,7,opt,name=offline,proto3" json:"offline,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncState) Reset() {
	*x = SyncState{}
	mi := &file_sync_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncState) ProtoMessage() {}

func (x *SyncState) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncState.ProtoReflect.Descriptor instead.
func (*SyncState) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{19}
}

func (x *SyncState) GetLastSync() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSync
	}
	return nil
}

func (x *SyncState) GetLocalTip() *SnapshotId {
	if x != nil {
		return x.LocalTip
	}
	return nil
}

func (x *SyncState) GetRemoteTip() *SnapshotId {
	if x != nil {
		return x.RemoteTip
	}
	return nil
}

func (x *SyncState) GetPendingStaged() uint32 {
	if x != nil {
		return x.PendingStaged
	}
	return 0
}

func (x *SyncState) GetPendingObjects() uint32 {
	if x != nil {
		return x.PendingObjects
	}
	return 0
}

func (x *SyncState) GetIsSyncing() bool {
	if x != nil {
		return x.IsSyncing
	}
	return false
}

func (x *SyncState) GetOffline() bool {
	if x != nil {
		return x.Offline
	}
	return false
}

// Envelope for sync messages. gRPC supersedes this for the bg<->server
// transport; this type is kept for parity with the Rust domain layer
// during the WT-PROTO migration. Once all callers move to direct gRPC
// calls, the envelope (and crates/worktree-protocol/src/feature/wire/)
// can be deleted.
type SyncEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   SyncMessageType        `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=worktree.sync.v1.SyncMessageType" json:"message_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sequence      uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncEnvelope) Reset() {
	*x = SyncEnvelope{}
	mi := &file_sync_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncEnvelope) ProtoMessage() {}

func (x *SyncEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncEnvelope.ProtoReflect.Descriptor instead.
func (*SyncEnvelope) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{20}
}

func (x *SyncEnvelope) GetMessageType() SyncMessageType {
	if x != nil {
		return x.MessageType
	}
	return SyncMessageType_SYNC_MESSAGE_TYPE_UNSPECIFIED
}

func (x *SyncEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SyncEnvelope) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SyncEnvelope) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// The server tip moved since the client's last pull.
type PushRejection_ConflictDetected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTip     *SnapshotId            `protobuf:"bytes,1,opt,name=server_tip,json=serverTip,proto3" json:"server_tip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRejection_ConflictDetected) Reset() {
	*x = PushRejection_ConflictDetected{}
	mi := &file_sync_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRejection_ConflictDetected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRejection_ConflictDetected) ProtoMessage() {}

func (x *PushRejection_ConflictDetected) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRejection_ConflictDetected.ProtoReflect.Descriptor instead.
func (*PushRejection_ConflictDetected) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{12, 0}
}

func (x *PushRejection_ConflictDetected) GetServerTip() *SnapshotId {
	if x != nil {
		return x.ServerTip
	}
	return nil
}

// A branch protection rule rejected the push.
type PushRejection_BranchProtection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          string                 `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRejection_BranchProtection) Reset() {
	*x = PushRejection_BranchProtection{}
	mi := &file_sync_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRejection_BranchProtection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRejection_BranchProtection) ProtoMessage() {}

func (x *PushRejection_BranchProtection) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRejection_BranchProtection.ProtoReflect.Descriptor instead.
func (*PushRejection_BranchProtection) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{12, 1}
}

func (x *PushRejection_BranchProtection) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

// Caller lacks the necessary permissions.
type PushRejection_AccessDenied struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRejection_AccessDenied) Reset() {
	*x = PushRejection_AccessDenied{}
	mi := &file_sync_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRejection_AccessDenied) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRejection_AccessDenied) ProtoMessage() {}

func (x *PushRejection_AccessDenied) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRejection_AccessDenied.ProtoReflect.Descriptor instead.
func (*PushRejection_AccessDenied) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{12, 2}
}

func (x *PushRejection_AccessDenied) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// A file in the push violates the configured license policy.
type PushRejection_LicenseViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	License       string                 `protobuf:"bytes,2,opt,name=license,proto3" json:"license,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRejection_LicenseViolation) Reset() {
	*x = PushRejection_LicenseViolation{}
	mi := &file_sync_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRejection_LicenseViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRejection_LicenseViolation) ProtoMessage() {}

func (x *PushRejection_LicenseViolation) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRejection_LicenseViolation.ProtoReflect.Descriptor instead.
func (*PushRejection_LicenseViolation) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{12, 3}
}

func (x *PushRejection_LicenseViolation) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PushRejection_LicenseViolation) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

// Required CI checks did not pass.
type PushRejection_CiChecksFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checks        []string               `protobuf:"bytes,1,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRejection_CiChecksFailed) Reset() {
	*x = PushRejection_CiChecksFailed{}
	mi := &file_sync_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRejection_CiChecksFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRejection_CiChecksFailed) ProtoMessage() {}

func (x *PushRejection_CiChecksFailed) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRejection_CiChecksFailed.ProtoReflect.Descriptor instead.
func (*PushRejection_CiChecksFailed) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{12, 4}
}

func (x *PushRejection_CiChecksFailed) GetChecks() []string {
	if x != nil {
		return x.Checks
	}
	return nil
}

// Branch protection requires more reviewers than the push has.
type PushRejection_ReviewRequired struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Required      uint32                 `protobuf:"varint,1,opt,name=required,proto3" json:"required,omitempty"`
	Current       uint32                 `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRejection_ReviewRequired) Reset() {
	*x = PushRejection_ReviewRequired{}
	mi := &file_sync_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRejection_ReviewRequired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRejection_ReviewRequired) ProtoMessage() {}

func (x *PushRejection_ReviewRequired) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRejection_ReviewRequired.ProtoReflect.Descriptor instead.
func (*PushRejection_ReviewRequired) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{12, 5}
}

func (x *PushRejection_ReviewRequired) GetRequired() uint32 {
	if x != nil {
		return x.Required
	}
	return 0
}

func (x *PushRejection_ReviewRequired) GetCurrent() uint32 {
	if x != nil {
		return x.Current
	}
	return 0
}

// Tenant quota exceeded.
type PushRejection_QuotaExceeded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         string                 `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRejection_QuotaExceeded) Reset() {
	*x = PushRejection_QuotaExceeded{}
	mi := &file_sync_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRejection_QuotaExceeded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRejection_QuotaExceeded) ProtoMessage() {}

func (x *PushRejection_QuotaExceeded) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRejection_QuotaExceeded.ProtoReflect.Descriptor instead.
func (*PushRejection_QuotaExceeded) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{12, 6}
}

func (x *PushRejection_QuotaExceeded) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

var File_sync_proto protoreflect.FileDescriptor

const file_sync_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sync.proto\x12\x10worktree.sync.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"%\n" +
	"\x06TreeId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05valueJ\x05\bd\x10\xc8\x01\")\n" +
	"\n" +
	"SnapshotId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05valueJ\x05\bd\x10\xc8\x01\"'\n" +
	"\bBranchId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05valueJ\x05\bd\x10\xc8\x01\"'\n" +
	"\bTenantId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05valueJ\x05\bd\x10\xc8\x01\"(\n" +
	"\tAccountId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05valueJ\x05\bd\x10\xc8\x01\"*\n" +
	"\vContentHash\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05valueJ\x05\bd\x10\xc8\x01\"K\n" +
	"\vHaveMessage\x125\n" +
	"\x06hashes\x18\x01 \x03(\v2\x1d.worktree.sync.v1.ContentHashR\x06hashesJ\x05\bd\x10\xc8\x01\"K\n" +
	"\vWantMessage\x125\n" +
	"\x06hashes\x18\x01 \x03(\v2\x1d.worktree.sync.v1.ContentHashR\x06hashesJ\x05\bd\x10\xc8\x01\"\x81\x01\n" +
	"\x12ObjectTransferPlan\x12E\n" +
	"\x0fobjects_to_send\x18\x01 \x03(\v2\x1d.worktree.sync.v1.ContentHashR\robjectsToSend\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x04R\ttotalSizeJ\x05\bd\x10\xc8\x01\"\x7f\n" +
	"\x10NegotiateRequest\x121\n" +
	"\x04have\x18\x01 \x01(\v2\x1d.worktree.sync.v1.HaveMessageR\x04have\x121\n" +
	"\x04want\x18\x02 \x01(\v2\x1d.worktree.sync.v1.WantMessageR\x04wantJ\x05\bd\x10\xc8\x01\"\xda\x03\n" +
	"\vPushRequest\x127\n" +
	"\ttenant_id\x18\x01 \x01(\v2\x1a.worktree.sync.v1.TenantIdR\btenantId\x121\n" +
	"\atree_id\x18\x02 \x01(\v2\x18.worktree.sync.v1.TreeIdR\x06treeId\x127\n" +
	"\tbranch_id\x18\x03 \x01(\v2\x1a.worktree.sync.v1.BranchIdR\bbranchId\x12\x1f\n" +
	"\vbranch_name\x18\x04 \x01(\tR\n" +
	"branchName\x12:\n" +
	"\aold_tip\x18\x05 \x01(\v2\x1c.worktree.sync.v1.SnapshotIdH\x00R\x06oldTip\x88\x01\x01\x125\n" +
	"\anew_tip\x18\x06 \x01(\v2\x1c.worktree.sync.v1.SnapshotIdR\x06newTip\x12C\n" +
	"\x0esnapshot_chain\x18\a \x03(\v2\x1c.worktree.sync.v1.SnapshotIdR\rsnapshotChain\x12:\n" +
	"\n" +
	"account_id\x18\b \x01(\v2\x1b.worktree.sync.v1.AccountIdR\taccountIdB\n" +
	"\n" +
	"\b_old_tipJ\x05\bd\x10\xc8\x01\"\xdf\x01\n" +
	"\fPushResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12O\n" +
	"\x10rejection_reason\x18\x02 \x01(\v2\x1f.worktree.sync.v1.PushRejectionH\x00R\x0frejectionReason\x88\x01\x01\x12:\n" +
	"\anew_tip\x18\x03 \x01(\v2\x1c.worktree.sync.v1.SnapshotIdH\x01R\x06newTip\x88\x01\x01B\x13\n" +
	"\x11_rejection_reasonB\n" +
	"\n" +
	"\b_new_tipJ\x05\bd\x10\xc8\x01\"\xd4\b\n" +
	"\rPushRejection\x12_\n" +
	"\x11conflict_detected\x18\x01 \x01(\v20.worktree.sync.v1.PushRejection.ConflictDetectedH\x00R\x10conflictDetected\x12_\n" +
	"\x11branch_protection\x18\x02 \x01(\v20.worktree.sync.v1.PushRejection.BranchProtectionH\x00R\x10branchProtection\x12S\n" +
	"\raccess_denied\x18\x03 \x01(\v2,.worktree.sync.v1.PushRejection.AccessDeniedH\x00R\faccessDenied\x12_\n" +
	"\x11license_violation\x18\x04 \x01(\v20.worktree.sync.v1.PushRejection.LicenseViolationH\x00R\x10licenseViolation\x12Z\n" +
	"\x10ci_checks_failed\x18\x05 \x01(\v2..worktree.sync.v1.PushRejection.CiChecksFailedH\x00R\x0eciChecksFailed\x12Y\n" +
	"\x0freview_required\x18\x06 \x01(\v2..worktree.sync.v1.PushRejection.ReviewRequiredH\x00R\x0ereviewRequired\x12V\n" +
	"\x0equota_exceeded\x18\a \x01(\v2-.worktree.sync.v1.PushRejection.QuotaExceededH\x00R\rquotaExceeded\x1aV\n" +
	"\x10ConflictDetected\x12;\n" +
	"\n" +
	"server_tip\x18\x01 \x01(\v2\x1c.worktree.sync.v1.SnapshotIdR\tserverTipJ\x05\bd\x10\xc8\x01\x1a-\n" +
	"\x10BranchProtection\x12\x12\n" +
	"\x04rule\x18\x01 \x01(\tR\x04ruleJ\x05\bd\x10\xc8\x01\x1a-\n" +
	"\fAccessDenied\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reasonJ\x05\bd\x10\xc8\x01\x1aG\n" +
	"\x10LicenseViolation\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\alicense\x18\x02 \x01(\tR\alicenseJ\x05\bd\x10\xc8\x01\x1a/\n" +
	"\x0eCiChecksFailed\x12\x16\n" +
	"\x06checks\x18\x01 \x03(\tR\x06checksJ\x05\bd\x10\xc8\x01\x1aM\n" +
	"\x0eReviewRequired\x12\x1a\n" +
	"\brequired\x18\x01 \x01(\rR\brequired\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\rR\acurrentJ\x05\bd\x10\xc8\x01\x1a,\n" +
	"\rQuotaExceeded\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\tR\x05limitJ\x05\bd\x10\xc8\x01B\b\n" +
	"\x06reasonJ\x05\bd\x10\xc8\x01\"\xee\x02\n" +
	"\vPullRequest\x127\n" +
	"\ttenant_id\x18\x01 \x01(\v2\x1a.worktree.sync.v1.TenantIdR\btenantId\x121\n" +
	"\atree_id\x18\x02 \x01(\v2\x18.worktree.sync.v1.TreeIdR\x06treeId\x127\n" +
	"\tbranch_id\x18\x03 \x01(\v2\x1a.worktree.sync.v1.BranchIdR\bbranchId\x12B\n" +
	"\vcurrent_tip\x18\x04 \x01(\v2\x1c.worktree.sync.v1.SnapshotIdH\x00R\n" +
	"currentTip\x88\x01\x01\x12:\n" +
	"\n" +
	"account_id\x18\x05 \x01(\v2\x1b.worktree.sync.v1.AccountIdR\taccountId\x12\x19\n" +
	"\x05depth\x18\x06 \x01(\rH\x01R\x05depth\x88\x01\x01B\x0e\n" +
	"\f_current_tipB\b\n" +
	"\x06_depthJ\x05\bd\x10\xc8\x01\"\x8c\x02\n" +
	"\fPullResponse\x12\x1f\n" +
	"\vhas_updates\x18\x01 \x01(\bR\n" +
	"hasUpdates\x12:\n" +
	"\anew_tip\x18\x02 \x01(\v2\x1c.worktree.sync.v1.SnapshotIdH\x00R\x06newTip\x88\x01\x01\x12C\n" +
	"\x0esnapshot_chain\x18\x03 \x03(\v2\x1c.worktree.sync.v1.SnapshotIdR\rsnapshotChain\x12G\n" +
	"\x10objects_to_fetch\x18\x04 \x03(\v2\x1d.worktree.sync.v1.ContentHashR\x0eobjectsToFetchB\n" +
	"\n" +
	"\b_new_tipJ\x05\bd\x10\xc8\x01\"\x99\x04\n" +
	"\x12StageUploadRequest\x127\n" +
	"\ttenant_id\x18\x01 \x01(\v2\x1a.worktree.sync.v1.TenantIdR\btenantId\x121\n" +
	"\atree_id\x18\x02 \x01(\v2\x18.worktree.sync.v1.TreeIdR\x06treeId\x127\n" +
	"\tbranch_id\x18\x03 \x01(\v2\x1a.worktree.sync.v1.BranchIdR\bbranchId\x12\x1f\n" +
	"\vbranch_name\x18\x04 \x01(\tR\n" +
	"branchName\x12=\n" +
	"\vsnapshot_id\x18\x05 \x01(\v2\x1c.worktree.sync.v1.SnapshotIdR\n" +
	"snapshotId\x12#\n" +
	"\rfiles_changed\x18\x06 \x03(\tR\ffilesChanged\x12\x1f\n" +
	"\vfiles_added\x18\a \x01(\rR\n" +
	"filesAdded\x12%\n" +
	"\x0efiles_modified\x18\b \x01(\rR\rfilesModified\x12#\n" +
	"\rfiles_deleted\x18\t \x01(\rR\ffilesDeleted\x12\x1d\n" +
	"\amessage\x18\n" +
	" \x01(\tH\x00R\amessage\x88\x01\x01\x12:\n" +
	"\n" +
	"account_id\x18\v \x01(\v2\x1b.worktree.sync.v1.AccountIdR\taccountIdB\n" +
	"\n" +
	"\b_messageJ\x05\bd\x10\xc8\x01\"]\n" +
	"\x13StageUploadResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_errorJ\x05\bd\x10\xc8\x01\"\xb4\x02\n" +
	"\x17AccessConfigSyncRequest\x127\n" +
	"\ttenant_id\x18\x01 \x01(\v2\x1a.worktree.sync.v1.TenantIdR\btenantId\x12C\n" +
	"\vconfig_type\x18\x02 \x01(\x0e2\".worktree.sync.v1.AccessConfigTypeR\n" +
	"configType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12>\n" +
	"\vconfig_hash\x18\x04 \x01(\v2\x1d.worktree.sync.v1.ContentHashR\n" +
	"configHash\x12:\n" +
	"\n" +
	"account_id\x18\x05 \x01(\v2\x1b.worktree.sync.v1.AccountIdR\taccountIdJ\x05\bd\x10\xc8\x01\"j\n" +
	"\x18AccessConfigSyncResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12+\n" +
	"\x11validation_errors\x18\x02 \x03(\tR\x10validationErrorsJ\x05\bd\x10\xc8\x01\"\x86\x03\n" +
	"\tSyncState\x12<\n" +
	"\tlast_sync\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\blastSync\x88\x01\x01\x12>\n" +
	"\tlocal_tip\x18\x02 \x01(\v2\x1c.worktree.sync.v1.SnapshotIdH\x01R\blocalTip\x88\x01\x01\x12@\n" +
	"\n" +
	"remote_tip\x18\x03 \x01(\v2\x1c.worktree.sync.v1.SnapshotIdH\x02R\tremoteTip\x88\x01\x01\x12%\n" +
	"\x0epending_staged\x18\x04 \x01(\rR\rpendingStaged\x12'\n" +
	"\x0fpending_objects\x18\x05 \x01(\rR\x0ependingObjects\x12\x1d\n" +
	"\n" +
	"is_syncing\x18\x06 \x01(\bR\tisSyncing\x12\x18\n" +
	"\aoffline\x18\a \x01(\bR\aofflineB\f\n" +
	"\n" +
	"_last_syncB\f\n" +
	"\n" +
	"_local_tipB\r\n" +
	"\v_remote_tipJ\x05\bd\x10\xc8\x01\"\xcb\x01\n" +
	"\fSyncEnvelope\x12D\n" +
	"\fmessage_type\x18\x01 \x01(\x0e2!.worktree.sync.v1.SyncMessageTypeR\vmessageType\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequenceJ\x05\bd\x10\xc8\x01*\x9f\x04\n" +
	"\x0fSyncMessageType\x12!\n" +
	"\x1dSYNC_MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eSYNC_MESSAGE_TYPE_STAGE_UPLOAD\x10\x01\x12\x1f\n" +
	"\x1bSYNC_MESSAGE_TYPE_STAGE_ACK\x10\x02\x12\"\n" +
	"\x1eSYNC_MESSAGE_TYPE_PUSH_REQUEST\x10\x03\x12#\n" +
	"\x1fSYNC_MESSAGE_TYPE_PUSH_RESPONSE\x10\x04\x12\"\n" +
	"\x1eSYNC_MESSAGE_TYPE_PULL_REQUEST\x10\x05\x12#\n" +
	"\x1fSYNC_MESSAGE_TYPE_PULL_RESPONSE\x10\x06\x12\x1f\n" +
	"\x1bSYNC_MESSAGE_TYPE_HAVE_WANT\x10\a\x12%\n" +
	"!SYNC_MESSAGE_TYPE_OBJECT_TRANSFER\x10\b\x12(\n" +
	"$SYNC_MESSAGE_TYPE_ACCESS_CONFIG_SYNC\x10\t\x12\x1e\n" +
	"\x1aSYNC_MESSAGE_TYPE_TAG_SYNC\x10\n" +
	"\x12\"\n" +
	"\x1eSYNC_MESSAGE_TYPE_CHUNK_UPLOAD\x10\v\x12$\n" +
	" SYNC_MESSAGE_TYPE_CHUNK_DOWNLOAD\x10\f\x12\x1a\n" +
	"\x16SYNC_MESSAGE_TYPE_PING\x10\r\x12\x1a\n" +
	"\x16SYNC_MESSAGE_TYPE_PONG\x10\x0e*\xe5\x01\n" +
	"\x10AccessConfigType\x12\"\n" +
	"\x1eACCESS_CONFIG_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ACCESS_CONFIG_TYPE_ROLES\x10\x01\x12\x1f\n" +
	"\x1bACCESS_CONFIG_TYPE_POLICIES\x10\x02\x12$\n" +
	" ACCESS_CONFIG_TYPE_TENANT_ACCESS\x10\x03\x12(\n" +
	"$ACCESS_CONFIG_TYPE_BRANCH_PROTECTION\x10\x04\x12\x1e\n" +
	"\x1aACCESS_CONFIG_TYPE_LICENSE\x10\x052\xb3\x03\n" +
	"\vSyncService\x12T\n" +
	"\x05Stage\x12$.worktree.sync.v1.StageUploadRequest\x1a%.worktree.sync.v1.StageUploadResponse\x12E\n" +
	"\x04Push\x12\x1d.worktree.sync.v1.PushRequest\x1a\x1e.worktree.sync.v1.PushResponse\x12E\n" +
	"\x04Pull\x12\x1d.worktree.sync.v1.PullRequest\x1a\x1e.worktree.sync.v1.PullResponse\x12U\n" +
	"\tNegotiate\x12\".worktree.sync.v1.NegotiateRequest\x1a$.worktree.sync.v1.ObjectTransferPlan\x12i\n" +
	"\x10SyncAccessConfig\x12).worktree.sync.v1.AccessConfigSyncRequest\x1a*.worktree.sync.v1.AccessConfigSyncResponseBJZHgithub.com/seanfilimon/worktree/services/server-go/internal/proto/syncpbb\x06proto3"

var (
	file_sync_proto_rawDescOnce sync.Once
	file_sync_proto_rawDescData []byte
)

func file_sync_proto_rawDescGZIP() []byte {
	file_sync_proto_rawDescOnce.Do(func() {
		file_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)))
	})
	return file_sync_proto_rawDescData
}

var file_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_sync_proto_goTypes = []any{
	(SyncMessageType)(0),                   // 0: worktree.sync.v1.SyncMessageType
	(AccessConfigType)(0),                  // 1: worktree.sync.v1.AccessConfigType
	(*TreeId)(nil),                         // 2: worktree.sync.v1.TreeId
	(*SnapshotId)(nil),                     // 3: worktree.sync.v1.SnapshotId
	(*BranchId)(nil),                       // 4: worktree.sync.v1.BranchId
	(*TenantId)(nil),                       // 5: worktree.sync.v1.TenantId
	(*AccountId)(nil),                      // 6: worktree.sync.v1.AccountId
	(*ContentHash)(nil),                    // 7: worktree.sync.v1.ContentHash
	(*HaveMessage)(nil),                    // 8: worktree.sync.v1.HaveMessage
	(*WantMessage)(nil),                    // 9: worktree.sync.v1.WantMessage
	(*ObjectTransferPlan)(nil),             // 10: worktree.sync.v1.ObjectTransferPlan
	(*NegotiateRequest)(nil),               // 11: worktree.sync.v1.NegotiateRequest
	(*PushRequest)(nil),                    // 12: worktree.sync.v1.PushRequest
	(*PushResponse)(nil),                   // 13: worktree.sync.v1.PushResponse
	(*PushRejection)(nil),                  // 14: worktree.sync.v1.PushRejection
	(*PullRequest)(nil),                    // 15: worktree.sync.v1.PullRequest
	(*PullResponse)(nil),                   // 16: worktree.sync.v1.PullResponse
	(*StageUploadRequest)(nil),             // 17: worktree.sync.v1.StageUploadRequest
	(*StageUploadResponse)(nil),            // 18: worktree.sync.v1.StageUploadResponse
	(*AccessConfigSyncRequest)(nil),        // 19: worktree.sync.v1.AccessConfigSyncRequest
	(*AccessConfigSyncResponse)(nil),       // 20: worktree.sync.v1.AccessConfigSyncResponse
	(*SyncState)(nil),                      // 21: worktree.sync.v1.SyncState
	(*SyncEnvelope)(nil),                   // 22: worktree.sync.v1.SyncEnvelope
	(*PushRejection_ConflictDetected)(nil), // 23: worktree.sync.v1.PushRejection.ConflictDetected
	(*PushRejection_BranchProtection)(nil), // 24: worktree.sync.v1.PushRejection.BranchProtection
	(*PushRejection_AccessDenied)(nil),     // 25: worktree.sync.v1.PushRejection.AccessDenied
	(*PushRejection_LicenseViolation)(nil), // 26: worktree.sync.v1.PushRejection.LicenseViolation
	(*PushRejection_CiChecksFailed)(nil),   // 27: worktree.sync.v1.PushRejection.CiChecksFailed
	(*PushRejection_ReviewRequired)(nil),   // 28: worktree.sync.v1.PushRejection.ReviewRequired
	(*PushRejection_QuotaExceeded)(nil),    // 29: worktree.sync.v1.PushRejection.QuotaExceeded
	(*timestamppb.Timestamp)(nil),          // 30: google.protobuf.Timestamp
}
var file_sync_proto_depIdxs = []int32{
	7,  // 0: worktree.sync.v1.HaveMessage.hashes:type_name -> worktree.sync.v1.ContentHash
	7,  // 1: worktree.sync.v1.WantMessage.hashes:type_name -> worktree.sync.v1.ContentHash
	7,  // 2: worktree.sync.v1.ObjectTransferPlan.objects_to_send:type_name -> worktree.sync.v1.ContentHash
	8,  // 3: worktree.sync.v1.NegotiateRequest.have:type_name -> worktree.sync.v1.HaveMessage
	9,  // 4: worktree.sync.v1.NegotiateRequest.want:type_name -> worktree.sync.v1.WantMessage
	5,  // 5: worktree.sync.v1.PushRequest.tenant_id:type_name -> worktree.sync.v1.TenantId
	2,  // 6: worktree.sync.v1.PushRequest.tree_id:type_name -> worktree.sync.v1.TreeId
	4,  // 7: worktree.sync.v1.PushRequest.branch_id:type_name -> worktree.sync.v1.BranchId
	3,  // 8: worktree.sync.v1.PushRequest.old_tip:type_name -> worktree.sync.v1.SnapshotId
	3,  // 9: worktree.sync.v1.PushRequest.new_tip:type_name -> worktree.sync.v1.SnapshotId
	3,  // 10: worktree.sync.v1.PushRequest.snapshot_chain:type_name -> worktree.sync.v1.SnapshotId
	6,  // 11: worktree.sync.v1.PushRequest.account_id:type_name -> worktree.sync.v1.AccountId
	14, // 12: worktree.sync.v1.PushResponse.rejection_reason:type_name -> worktree.sync.v1.PushRejection
	3,  // 13: worktree.sync.v1.PushResponse.new_tip:type_name -> worktree.sync.v1.SnapshotId
	23, // 14: worktree.sync.v1.PushRejection.conflict_detected:type_name -> worktree.sync.v1.PushRejection.ConflictDetected
	24, // 15: worktree.sync.v1.PushRejection.branch_protection:type_name -> worktree.sync.v1.PushRejection.BranchProtection
	25, // 16: worktree.sync.v1.PushRejection.access_denied:type_name -> worktree.sync.v1.PushRejection.AccessDenied
	26, // 17: worktree.sync.v1.PushRejection.license_violation:type_name -> worktree.sync.v1.PushRejection.LicenseViolation
	27, // 18: worktree.sync.v1.PushRejection.ci_checks_failed:type_name -> worktree.sync.v1.PushRejection.CiChecksFailed
	28, // 19: worktree.sync.v1.PushRejection.review_required:type_name -> worktree.sync.v1.PushRejection.ReviewRequired
	29, // 20: worktree.sync.v1.PushRejection.quota_exceeded:type_name -> worktree.sync.v1.PushRejection.QuotaExceeded
	5,  // 21: worktree.sync.v1.PullRequest.tenant_id:type_name -> worktree.sync.v1.TenantId
	2,  // 22: worktree.sync.v1.PullRequest.tree_id:type_name -> worktree.sync.v1.TreeId
	4,  // 23: worktree.sync.v1.PullRequest.branch_id:type_name -> worktree.sync.v1.BranchId
	3,  // 24: worktree.sync.v1.PullRequest.current_tip:type_name -> worktree.sync.v1.SnapshotId
	6,  // 25: worktree.sync.v1.PullRequest.account_id:type_name -> worktree.sync.v1.AccountId
	3,  // 26: worktree.sync.v1.PullResponse.new_tip:type_name -> worktree.sync.v1.SnapshotId
	3,  // 27: worktree.sync.v1.PullResponse.snapshot_chain:type_name -> worktree.sync.v1.SnapshotId
	7,  // 28: worktree.sync.v1.PullResponse.objects_to_fetch:type_name -> worktree.sync.v1.ContentHash
	5,  // 29: worktree.sync.v1.StageUploadRequest.tenant_id:type_name -> worktree.sync.v1.TenantId
	2,  // 30: worktree.sync.v1.StageUploadRequest.tree_id:type_name -> worktree.sync.v1.TreeId
	4,  // 31: worktree.sync.v1.StageUploadRequest.branch_id:type_name -> worktree.sync.v1.BranchId
	3,  // 32: worktree.sync.v1.StageUploadRequest.snapshot_id:type_name -> worktree.sync.v1.SnapshotId
	6,  // 33: worktree.sync.v1.StageUploadRequest.account_id:type_name -> worktree.sync.v1.AccountId
	5,  // 34: worktree.sync.v1.AccessConfigSyncRequest.tenant_id:type_name -> worktree.sync.v1.TenantId
	1,  // 35: worktree.sync.v1.AccessConfigSyncRequest.config_type:type_name -> worktree.sync.v1.AccessConfigType
	7,  // 36: worktree.sync.v1.AccessConfigSyncRequest.config_hash:type_name -> worktree.sync.v1.ContentHash
	6,  // 37: worktree.sync.v1.AccessConfigSyncRequest.account_id:type_name -> worktree.sync.v1.AccountId
	30, // 38: worktree.sync.v1.SyncState.last_sync:type_name -> google.protobuf.Timestamp
	3,  // 39: worktree.sync.v1.SyncState.local_tip:type_name -> worktree.sync.v1.SnapshotId
	3,  // 40: worktree.sync.v1.SyncState.remote_tip:type_name -> worktree.sync.v1.SnapshotId
	0,  // 41: worktree.sync.v1.SyncEnvelope.message_type:type_name -> worktree.sync.v1.SyncMessageType
	30, // 42: worktree.sync.v1.SyncEnvelope.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 43: worktree.sync.v1.PushRejection.ConflictDetected.server_tip:type_name -> worktree.sync.v1.SnapshotId
	17, // 44: worktree.sync.v1.SyncService.Stage:input_type -> worktree.sync.v1.StageUploadRequest
	12, // 45: worktree.sync.v1.SyncService.Push:input_type -> worktree.sync.v1.PushRequest
	15, // 46: worktree.sync.v1.SyncService.Pull:input_type -> worktree.sync.v1.PullRequest
	11, // 47: worktree.sync.v1.SyncService.Negotiate:input_type -> worktree.sync.v1.NegotiateRequest
	19, // 48: worktree.sync.v1.SyncService.SyncAccessConfig:input_type -> worktree.sync.v1.AccessConfigSyncRequest
	18, // 49: worktree.sync.v1.SyncService.Stage:output_type -> worktree.sync.v1.StageUploadResponse
	13, // 50: worktree.sync.v1.SyncService.Push:output_type -> worktree.sync.v1.PushResponse
	16, // 51: worktree.sync.v1.SyncService.Pull:output_type -> worktree.sync.v1.PullResponse
	10, // 52: worktree.sync.v1.SyncService.Negotiate:output_type -> worktree.sync.v1.ObjectTransferPlan
	20, // 53: worktree.sync.v1.SyncService.SyncAccessConfig:output_type -> worktree.sync.v1.AccessConfigSyncResponse
	49, // [49:54] is the sub-list for method output_type
	44, // [44:49] is the sub-list for method input_type
	44, // [44:44] is the sub-list for extension type_name
	44, // [44:44] is the sub-list for extension extendee
	0,  // [0:44] is the sub-list for field type_name
}

func init() { file_sync_proto_init() }
func file_sync_proto_init() {
	if File_sync_proto != nil {
		return
	}
	file_sync_proto_msgTypes[10].OneofWrappers = []any{}
	file_sync_proto_msgTypes[11].OneofWrappers = []any{}
	file_sync_proto_msgTypes[12].OneofWrappers = []any{
		(*PushRejection_ConflictDetected_)(nil),
		(*PushRejection_BranchProtection_)(nil),
		(*PushRejection_AccessDenied_)(nil),
		(*PushRejection_LicenseViolation_)(nil),
		(*PushRejection_CiChecksFailed_)(nil),
		(*PushRejection_ReviewRequired_)(nil),
		(*PushRejection_QuotaExceeded_)(nil),
	}
	file_sync_proto_msgTypes[13].OneofWrappers = []any{}
	file_sync_proto_msgTypes[14].OneofWrappers = []any{}
	file_sync_proto_msgTypes[15].OneofWrappers = []any{}
	file_sync_proto_msgTypes[16].OneofWrappers = []any{}
	file_sync_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_proto_goTypes,
		DependencyIndexes: file_sync_proto_depIdxs,
		EnumInfos:         file_sync_proto_enumTypes,
		MessageInfos:      file_sync_proto_msgTypes,
	}.Build()
	File_sync_proto = out.File
	file_sync_proto_goTypes = nil
	file_sync_proto_depIdxs = nil
}
