// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: sync.proto

// W0rkTree sync protocol — wire format for communication between
// the local bgprocess (worktree-bg) and the remote server (worktree-server,
// future Go impl at services/server-go/).
//
// Mirrors the hand-coded Rust types in
//   crates/worktree-protocol/src/feature/sync_protocol.rs
// which remain alongside this codegen output during the WT-PROTO-* migration.
//
// Conventions: see crates/worktree-protocol/proto/CONVENTIONS.md
//   - all IDs are wrapped messages (cross-language type safety)
//   - field tag 100-199 is reserved on every message for additive expansion
//   - timestamps use google.protobuf.Timestamp
//   - payload-bearing Rust enums map to proto `oneof`; unit-only Rust enums
//     map to proto `enum` with _UNSPECIFIED = 0.

package syncpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncService_Stage_FullMethodName            = "/worktree.sync.v1.SyncService/Stage"
	SyncService_Push_FullMethodName             = "/worktree.sync.v1.SyncService/Push"
	SyncService_Pull_FullMethodName             = "/worktree.sync.v1.SyncService/Pull"
	SyncService_Negotiate_FullMethodName        = "/worktree.sync.v1.SyncService/Negotiate"
	SyncService_SyncAccessConfig_FullMethodName = "/worktree.sync.v1.SyncService/SyncAccessConfig"
)

// SyncServiceClient is the client API for SyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncServiceClient interface {
	// Upload a staged snapshot for team visibility.
	Stage(ctx context.Context, in *StageUploadRequest, opts ...grpc.CallOption) (*StageUploadResponse, error)
	// Push a branch tip with conflict detection.
	Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error)
	// Pull updates from the server (delta sync).
	Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (*PullResponse, error)
	// Negotiate which objects to transfer (have/want delta).
	Negotiate(ctx context.Context, in *NegotiateRequest, opts ...grpc.CallOption) (*ObjectTransferPlan, error)
	// Sync access config changes (roles, policies, branch protection, ...).
	SyncAccessConfig(ctx context.Context, in *AccessConfigSyncRequest, opts ...grpc.CallOption) (*AccessConfigSyncResponse, error)
}

type syncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncServiceClient(cc grpc.ClientConnInterface) SyncServiceClient {
	return &syncServiceClient{cc}
}

func (c *syncServiceClient) Stage(ctx context.Context, in *StageUploadRequest, opts ...grpc.CallOption) (*StageUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StageUploadResponse)
	err := c.cc.Invoke(ctx, SyncService_Stage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, SyncService_Push_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (*PullResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullResponse)
	err := c.cc.Invoke(ctx, SyncService_Pull_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) Negotiate(ctx context.Context, in *NegotiateRequest, opts ...grpc.CallOption) (*ObjectTransferPlan, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjectTransferPlan)
	err := c.cc.Invoke(ctx, SyncService_Negotiate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) SyncAccessConfig(ctx context.Context, in *AccessConfigSyncRequest, opts ...grpc.CallOption) (*AccessConfigSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessConfigSyncResponse)
	err := c.cc.Invoke(ctx, SyncService_SyncAccessConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncServiceServer is the server API for SyncService service.
// All implementations must embed UnimplementedSyncServiceServer
// for forward compatibility.
type SyncServiceServer interface {
	// Upload a staged snapshot for team visibility.
	Stage(context.Context, *StageUploadRequest) (*StageUploadResponse, error)
	// Push a branch tip with conflict detection.
	Push(context.Context, *PushRequest) (*PushResponse, error)
	// Pull updates from the server (delta sync).
	Pull(context.Context, *PullRequest) (*PullResponse, error)
	// Negotiate which objects to transfer (have/want delta).
	Negotiate(context.Context, *NegotiateRequest) (*ObjectTransferPlan, error)
	// Sync access config changes (roles, policies, branch protection, ...).
	SyncAccessConfig(context.Context, *AccessConfigSyncRequest) (*AccessConfigSyncResponse, error)
	mustEmbedUnimplementedSyncServiceServer()
}

// UnimplementedSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncServiceServer struct{}

func (UnimplementedSyncServiceServer) Stage(context.Context, *StageUploadRequest) (*StageUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stage not implemented")
}
func (UnimplementedSyncServiceServer) Push(context.Context, *PushRequest) (*PushResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedSyncServiceServer) Pull(context.Context, *PullRequest) (*PullResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Pull not implemented")
}
func (UnimplementedSyncServiceServer) Negotiate(context.Context, *NegotiateRequest) (*ObjectTransferPlan, error) {
	return nil, status.Error(codes.Unimplemented, "method Negotiate not implemented")
}
func (UnimplementedSyncServiceServer) SyncAccessConfig(context.Context, *AccessConfigSyncRequest) (*AccessConfigSyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncAccessConfig not implemented")
}
func (UnimplementedSyncServiceServer) mustEmbedUnimplementedSyncServiceServer() {}
func (UnimplementedSyncServiceServer) testEmbeddedByValue()                     {}

// UnsafeSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncServiceServer will
// result in compilation errors.
type UnsafeSyncServiceServer interface {
	mustEmbedUnimplementedSyncServiceServer()
}

func RegisterSyncServiceServer(s grpc.ServiceRegistrar, srv SyncServiceServer) {
	// If the following call panics, it indicates UnimplementedSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncService_ServiceDesc, srv)
}

func _SyncService_Stage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StageUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).Stage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_Stage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).Stage(ctx, req.(*StageUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_Push_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_Pull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).Pull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_Pull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).Pull(ctx, req.(*PullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_Negotiate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NegotiateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).Negotiate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_Negotiate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).Negotiate(ctx, req.(*NegotiateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_SyncAccessConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessConfigSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).SyncAccessConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_SyncAccessConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).SyncAccessConfig(ctx, req.(*AccessConfigSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncService_ServiceDesc is the grpc.ServiceDesc for SyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "worktree.sync.v1.SyncService",
	HandlerType: (*SyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stage",
			Handler:    _SyncService_Stage_Handler,
		},
		{
			MethodName: "Push",
			Handler:    _SyncService_Push_Handler,
		},
		{
			MethodName: "Pull",
			Handler:    _SyncService_Pull_Handler,
		},
		{
			MethodName: "Negotiate",
			Handler:    _SyncService_Negotiate_Handler,
		},
		{
			MethodName: "SyncAccessConfig",
			Handler:    _SyncService_SyncAccessConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sync.proto",
}
